# 포트 설정
server.port=8080

# 수동 Bean이 자동 Bean을 오버라이딩할 수 있도록 허용
spring.main.allow-bean-definition-overriding=true

# Open-Session-In-View 설정
spring.jpa.open-in-view=false

# 데이터베이스 연결 정보
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WSOP_Base;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=9449966Ab
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MyBatis 설정
#mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.mapper-locations=classpath:egovframework/sqlmap/base/mappers/**/*.xml
# VO 클래스 경로
mybatis.type-aliases-package=egovframework.base.model.*

# 로그인 정책
login.auto-login=false
login.external-login=http://www.internalune.com:8088/api/Account

# 비밀번호 정책
# 대문자 포함 여부
password.policy.need-uppercase=false
# 소문자 포함 여부
password.policy.need-lowercase=false
# 숫자 포함 여부
password.policy.need-number=false
# 특수문자 포함 여부
password.policy.need-character=false
# 입력가능한 특수문자
password.policy.allow-characters=-_
# 최소길이
password.policy.minimum-length=5
# 최대길이
password.policy.maximum-length=10