<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Utility\dnsExcelReport\dnsExcelReport.csproj" />
    <ProjectReference Include="..\Account\Base.Account.IBLL\Base.Account.IBLL.csproj" />
    <ProjectReference Include="..\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\History\Base.History.IBLL\Base.History.IBLL.csproj" />
    <ProjectReference Include="..\SDMS\Base.SDMS.IBLL\Base.SDMS.IBLL.csproj" />
    <ProjectReference Include="..\SensorSimulator\Base.SensorSimulator.IBLL\Base.SensorSimulator.IBLL.csproj" />
    <ProjectReference Include="..\Settings\Base.Settings.IBLL\Base.Settings.IBLL.csproj" />
    <ProjectReference Include="..\SOPManager\Base.SOPManager.IBLL\Base.SOPManager.IBLL.csproj" />
    <ProjectReference Include="..\SOPSimulator\Base.SOPSimulator.IBLL\Base.SOPSimulator.IBLL.csproj" />
    <ProjectReference Include="..\TeamEditor\Base.TeamEditor.IBLL\Base.TeamEditor.IBLL.csproj" />
    <ProjectReference Include="..\Weather\Base.Weather.IBLL\Base.Weather.IBLL.csproj" />
  </ItemGroup>

</Project>
