<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Content Remove="$(SpaRoot)**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\esdk\workspace\dnsGeometry\dnsGeometry\dnsGeometry.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\esdk\workspace\DNS_DBUtil\DNS_DBUtil\dnsDBUtil.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Common\Common.BLL\Common.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Common\Common.DAL\Common.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Common\Common.IDAL\Common.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Common\Common.Model\Common.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Dashboard\Dashboard.BLL\Dashboard.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Dashboard\Dashboard.DAL\Dashboard.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Dashboard\Dashboard.IDAL\Dashboard.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Dashboard\Dashboard.Model\Dashboard.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\DNS\dnsCommunicateSopServer\dnsCommunicateSopServer.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\DNS\dnsData\dnsData.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\DNS\dnsEmail\dnsEmail\dnsEmail.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\DNS\dnsSMS\dnsSMS\dnsSMS.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\DNS\dnsSopID\dnsSopID.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\History\History.BLL\History.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SDMS\SDMS.BLL\SDMS.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SDMS\SDMS.DAL\SDMS.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SDMS\SDMS.IDAL\SDMS.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SDMS\SDMS.Model\SDMS.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPManager\SOPManager.BLL\SOPManager.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPManager\SOPManager.DAL\SOPManager.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPManager\SOPManager.IDAL\SOPManager.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPManager\SOPManager.Model\SOPManager.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPSimulator\SOPSimulator.BLL\SOPSimulator.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPSimulator\SOPSimulator.DAL\SOPSimulator.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\SOPSimulator\SOPSimulator.IDAL\SOPSimulator.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\TeamEditor\TeamEditor.BLL\TeamEditor.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\TeamEditor\TeamEditor.DAL\TeamEditor.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\TeamEditor\TeamEditor.IDAL\TeamEditor.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\TeamEditor\TeamEditor.Model\TeamEditor.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Weather\Weather.BLL\Weather.BLL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Weather\Weather.DAL\Weather.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Weather\Weather.IDAL\Weather.IDAL.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\UnESolution2022\src\SOP7\Weather\Weather.Model\Weather.Model.csproj" />
    <ProjectReference Include="..\..\..\..\..\esdk\dnsDapperDBUtil\dnsDapperDBUtil\dnsDapperDBUtil.csproj" />
    <ProjectReference Include="..\..\..\Base\Account\Base.Account.BLL\Base.Account.BLL.csproj" />
    <ProjectReference Include="..\..\..\Base\Account\Base.Account.IBLL\Base.Account.IBLL.csproj" />
    <ProjectReference Include="..\..\..\Base\Base.Controller\Base.Controller.csproj" />
    <ProjectReference Include="..\..\..\Base\Base.DAL\Base.DAL.csproj" />
    <ProjectReference Include="..\..\..\Base\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\..\..\Base\SOPManager\Base.SOPManager.BLL\Base.SOPManager.BLL.csproj" />
    <ProjectReference Include="..\..\..\Base\SOPManager\Base.SOPManager.IBLL\Base.SOPManager.IBLL.csproj" />
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)build\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
