<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\esdk\dnsDapperDBUtil\dnsDapperDBUtil\dnsDapperDBUtil.csproj" />
    <ProjectReference Include="..\..\Base\Base.DAL\Base.DAL.csproj" />
    <ProjectReference Include="..\..\Base\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\..\Base\SDMS\Base.SDMS.IBLL\Base.SDMS.IBLL.csproj" />
    <ProjectReference Include="..\..\Utility\dnsExcelReport\dnsExcelReport.csproj" />
    <ProjectReference Include="..\..\Utility\Response\Response.csproj" />
    <ProjectReference Include="..\dnsDataKftc\dnsDataKftc.csproj" />
    <ProjectReference Include="..\Kftc.Model\Kftc.Model.csproj" />
  </ItemGroup>

</Project>
