<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Utility\Response\Response.csproj" />
    <ProjectReference Include="..\..\SDMS\Base.SDMS.IBLL\Base.SDMS.IBLL.csproj" />
    <ProjectReference Include="..\..\SOPWebServer\SOPWebServer.IBLL\SOPWebServer.IBLL.csproj" />
    <ProjectReference Include="..\Base.AlarmService.IBLL\Base.AlarmService.IBLL.csproj" />
  </ItemGroup>

</Project>
