<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\esdk\dnsSMS\dnsSMS\dnsSMS.csproj" />
    <ProjectReference Include="..\..\..\Utility\dnsData\dnsData2.csproj" />
    <ProjectReference Include="..\..\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\SOPWebServer.IBLL\SOPWebServer.IBLL.csproj" />
  </ItemGroup>

</Project>
