<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dnsDapperDBUtil\dnsDapperDBUtil\dnsDapperDBUtil.csproj" />
    <ProjectReference Include="..\DapperSample.IDAL\DapperSample.IDAL.csproj" />
  </ItemGroup>

</Project>
