<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <UserSecretsId>dotnet-BusanSensorService-FF75C2BA-34FC-4B55-96E1-9B72DD091D8A</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.22"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BusanSensorServer\BusanSensorServer.csproj" />
    </ItemGroup>
</Project>
