<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Base\Base.DAL\Base.DAL.csproj" />
    <ProjectReference Include="..\..\..\..\Base\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\..\..\..\Base\SensorControlServer\dnsPipeHelper\dnsPipeHelper.csproj" />
    <ProjectReference Include="..\..\..\..\Base\SensorControlServer\dnsSensorServer\dnsSensorServer.csproj" />
    <ProjectReference Include="..\..\..\..\Utility\dnsData\dnsData2.csproj" />
    <ProjectReference Include="..\..\..\Soulbrain.Model\Soulbrain.Model.csproj" />
  </ItemGroup>

</Project>