<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\esdk\dnsDapperDBUtil\dnsDapperDBUtil\dnsDapperDBUtil.csproj" />
    <ProjectReference Include="..\..\..\..\..\esdk\dnsEmail\dnsEmail\dnsEmail.csproj" />
    <ProjectReference Include="..\..\..\..\..\esdk\dnsSMS\dnsSMS\dnsSMS.csproj" />
    <ProjectReference Include="..\..\..\Base\Account\Base.Account.IBLL\Base.Account.IBLL.csproj" />
    <ProjectReference Include="..\..\..\Base\Base.Model\Base.Model.csproj" />
    <ProjectReference Include="..\..\..\Utility\dnsData\dnsData2.csproj" />
    <ProjectReference Include="..\..\..\Utility\Response\Response.csproj" />
  </ItemGroup>

</Project>
